name: Upload screenshot
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: http://ww7.6d-vision.com/scene-labeling?usid=19&utid=19069741812
          output: web.png
          
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://whatismyipaddress.com/
          output: ip.png
          mode: page
          
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://ipinfo.io/what-is-my-ip
          output: ip2.png
          mode: page
          
      - run: mkdir web && cd web
      - run: wget --wait=2 --level=inf --limit-rate=20K --recursive --page-requisites --user-agent=Mozilla --no-parent --convert-links --adjust-extension --no-clobber -e robots=off http://www.6d-vision.com
      - run: cd ..
      
      - name: 'Tar files'
        run: tar -cvzf file.tar.gz *
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-screenshot
          path: file.tar.gz  #${{ github.workspace }}/*.png
          compression-level: 9 # maximum compression
          retention-days: 2
